project_id = "nbvijawmjkycyweioglk"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true

[functions.moderate-image]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.text-to-speech-bestie]
verify_jwt = true

[functions.update-user-role]
verify_jwt = true

[functions.create-sponsorship-checkout]
verify_jwt = false

[functions.verify-sponsorship-payment]
verify_jwt = true

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.check-stripe-connect-status]
verify_jwt = true