project_id = "nbvijawmjkycyweioglk"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true

[functions.moderate-image]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true